### ISSUE TITLE
Errors when running 

### ISSUE THREAD

**Issue by jendrik20** [beamzer/ScirtScan#1]
The tool looks interesting but I get two errors when running scirtscan  

I use windows 10 and ran the tool with python 3 in a conda environment (with pip installed). I installed shcheck and sslabs with pip. I cloned scirtscan and sslabs-scan to the environment folder.   

`python .\scirtscan.py -d websites.txt`

```
========== https://www.google.nl
[WinError 193] %1 is geen geldige Win32-toepassing
check_versioninfo, record inserted into website_checks  1
error_check, record inserted into website_checks  1
robots_check, record inserted into website_checks  0
security.txt check, record inserted into website_checks  1
[WinError 2] Het systeem kan het opgegeven bestand niet vinden
```

Translated: [WinError 193] %1 is not a valid Win32-application
Translated: [WinError 2] %The system cannot find the specified file

**Comment by beamzer** [comment]
Looks like shcheck and ssllabs-scan can't be found. I guess if you do a
> conda list

they will show up, since the are installed. You could try
> where shcheck

to find out what the path is of the program and then modify scirtscan.py and prepend the path to shcheck.py ?

**Comment by jendrik20** [comment]
I checked both. It turns out that shcheck can be found, which makes sense as I installed it with pip from the standard repos. Changing scirtscan.py on line 104 to an invalid path as a test changes the first WinError from 193 to 2. 

ssllabs-scan-v3 could not be found. Changing 'ssllabs-scan-v3'  on line 289 to '.\\MyValidPath\\ssllabs-scan-v3.go' changed the second WinError from 2 to 193.

```
========== https://www.google.nl
[WinError 193] %1 is geen geldige Win32-toepassing
check_versioninfo, record inserted into website_checks  1
error_check, record inserted into website_checks  1
robots_check, record inserted into website_checks  0
security.txt check, record inserted into website_checks  1
[WinError 193] %1 is geen geldige Win32-toepassing
```

I also installed go by the msi installer from the [website](https://go.dev/doc/install), which can be found by windows. It wasn't in your readme but I saw it on the ssllabs-scan git page. 

```
go version
go version go1.20.1 windows/amd64
```
Could it be that I need some python package to work with go? Or is there some other issue why it throws the WinError 193? 

My python version:

```
python
Python 3.10.9 | packaged by conda-forge | (main, Jan 11 2023, 15:15:40) [MSC v.1916 64 bit (AMD64)] on win32
```

**Comment by beamzer** [comment]
Zelf werk ik met python op Linux en MacOS, maar ik heb even geprobeerd op Windows 10 python vanuit Conda te installeren. Als ik dan een virtual environment aanmaak genaamd scirtscan en daarin de installaties doe van de pakketten in requirements.txt
> pip install -r requirements.txt

en shcheck installeer
> pip install shcheck

Dan kan ik met
> pip show shcheck -f

Zien waar shcheck is geinstalleerd en verifiëren dat ik dat kan uitvoeren:
> python D:\SW\MiniConda\envs\scirtscan\Lib\site-packages\shcheck.py

Dat geeft dan netjes output. In scirtscan.py heb ik de regel aangepast die shcheck aanroept naar:
> process = subprocess.run(['D:\SW\MiniConda\python.exe', 'D:\SW\MiniConda\envs\scirtscan\Lib\site-packages\shcheck.py','-j', url], stdout=subprocess.PIPE, stderr=subprocess.PIPE)

en alle andere functies uitgecommentarieerd behalve
> header_check(website)

Dat geeft voor mij onder windows dan een werkend resultaat:
> python scirtscan-win.py -d websites.txt
debug output activated
websites will be read from: websites.txt
Connected to database 20230225\websites.db.
========== https://www.google.com
header_check, record inserted into website_checks  0
========== https://www.microsoft.com
header_check, record inserted into website_checks  1
========== https://www.apple.com
header_check, record inserted into website_checks  1

shcheck.py is maar een programma, maar ssllabs heeft wat meer afhankelijkheden. Waarschijnlijk moet je de environment variabelen (PYTHONPATH, PYTHONHOME, ..) die python -h teruggeeft laten wijzen naar de goede installatie directories waar pip de packages heeft geinstalleerd. Laat mij nog even weten of je dat dan werkend kan krijgen zo.

**Comment by jendrik20** [comment]
Ik heb nu de verschillende functies geprobeerd. De sleutel was daar dus python.exe aan te roepen bij header_check. 
Alle functies behalve ssllabs-scan werken verder voor mij voor de website waarvoor ik het zelf wil gebruiken. Echter werken niet alle functies bij alle websites uit het testbestand. 

header_check, robots_check en security.txt lijken **wel** consistent te werken. check_versioninfo en error_check werken **niet** op alle sites. Iig niet bij www.apple.com en www.microsoft.com, maar dus wel bij www.google.com.

Ik krijg de volgende errors

```
Traceback (most recent call last):
File "MyCondaEnvPath\ScirtScan\scirtscan.py", line 370, in <module>                     check_versioninfo(url)                                                                                                
File "MyCondaEnvPath\ScirtScan\scirtscan.py", line 163, in check_versioninfo            outfile.write(result + "\n")                                                                                        
UnboundLocalError: local variable 'result' referenced before assignment
```

```
Traceback (most recent call last):                                                                                        
File "MyCondaEnvPath\ScirtScan\scirtscan.py", line 371, in <module>                     error_check(url)                                                                                                      
File "MyCondaEnvPath\ScirtScan\scirtscan.py", line 265, in error_check                  outfile.write(str(soup))                                                                                              
File "MyCondaEnvPath\lib\encodings\cp1252.py", line 19, in encode                       return codecs.charmap_encode(input,self.errors,encoding_table)[0]                                                   
UnicodeEncodeError: 'charmap' codec can't encode characters in position 3513-3514: character maps to <undefined>
```
Daarnaast merkte ik dat het uitmaakt of ik een website met www. begin of niet. Als het webadres website.com betreft, en daarnaartoe redirect, ook als je www.website.com in de adresbalk invoert, krijg ik een error als ik deze als www.website.com in de txt zet. 

Ik heb dit overigens getest met de versie van de eerste melding, niet met de update die je inmiddels hebt gecommit.  

Ten slotte kwam ik voor [ssllabs-scan uit op een andere git repository](https://github.com/kyhau/ssllabs-scan) die voor ssllabs-scan een python package heeft geschreven en probleemloos met windows integreerd. Hier zitten wel de header scan die je met scirtscan ook uitvoert mbv ssllabs, maar niet de andere scans die je zelf in je tool hebt opgenomen. Mogelijk dat dit interessant is als alternatieve requirement voor sslabs/sslabs-scan.

**Comment by beamzer** [comment]
Will change back to English because other people with the same problems might benefit. 
I just uploaded v1.3 which has removed the dependency on the qualys ssllabs-scan tool, because the check is now done native form python by using the SSLtest API. I will probably also remove the dependency on shcheck.py because that will make life easier when installing the tool, but this will be in v1.4
For other new features, see the changelog.

**Comment by beamzer** [comment]
Version 1.4 had the dependency vo shcheck removed. All checks are now done in the main python code, except if you want to use testssl.sh instead of Qualys ssltest. Version is now at 2.0 with lots of new functions.
I am going to close the issue for now, let me know if you'r still running into problems
