### ISSUE TITLE
local variable 'result' referenced before assignment

### ISSUE THREAD

**Issue by ebrongers** [beamzer/ScirtScan#2]
Nice script Beamzer!
but .....
In the function  check_versioninfo(url) I got an error:

......@ubuntu-i5:~/PycharmProjects/ScirtScan$ python3 scirtscan.py websites.txt 
Traceback (most recent call last):
  File "/home/....../PycharmProjects/ScirtScan/scirtscan.py", line 373, in <module>
    check_versioninfo(url)
  File "/home/....../PycharmProjects/ScirtScan/scirtscan.py", line 163, in check_versioninfo
    outfile.write(result + "\n")
**UnboundLocalError: local variable 'result' referenced before assignment**

also variable check_version in same function

I solved this by inserting a declaration at line 146 of scirtscan.py to declare the variables.
----------------snip
   result = "NOK"
   check_version = 0
----------------snip

**Comment by beamzer** [comment]
Hi Eric,
Thanks for submitting this, i ran into the same error myself ;) The code now is changed to 

> def check_versioninfo(url):
>     try:   
>        result = "OK"       # we'll assume OK unless proven otherwise  
>        check_version = 1  

That should fix this bug. The detection of version info in the HTTP headers is still very inmature. I hope that as scirtscan is used more we can improve the detection by using it on various websites.

**Comment by ebrongers** [comment]
Thanx Ewald

Met vr gr
Eric Brongers

Verzonden: woensdag 22 februari 2023 14:39
Aan: beamzer/ScirtScan ***@***.***>

Onderwerp: Re: [beamzer/ScirtScan] local variable 'result' referenced before assignment (Issue #2)


Hi Eric,
Thanks for submitting this, i ran into the same error myself ;) The code now is changed to

def check_versioninfo(url):
try:
result = "OK" # we'll assume OK unless proven otherwise
check_version = 1

That should fix this bug. The detection of version info in the HTTP headers is still very inmature. I hope that as scirtscan is used more we can improve the detection by using it on various websites.
